In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix


In [2]:

h_train = pd.read_csv('./train_h.csv', header= None)
h_train['label'] = 0
y_train = pd.read_csv('./train_y.csv', header= None)
y_train['label'] =1
b_train = pd.read_csv('./train_b.csv', header= None)
b_train['label'] =2
h_test = pd.read_csv('./test_h.csv', header= None)
h_test['label'] = 0
y_test = pd.read_csv('./test_y.csv', header= None)
y_test['label'] = 1
b_test = pd.read_csv('./test_b.csv', header= None)
b_test['label'] = 2
print(
    h_train.shape,
    y_train.shape,
    b_train.shape,
    h_test.shape,
    y_test.shape,
    b_test.shape
)



(264, 1775) (440, 1775) (80, 1775) (30, 1775) (34, 1775) (31, 1775)


In [3]:
train=np.concatenate((h_train,y_train,b_train),0)
test=np.concatenate((h_test,y_test,b_test),0)

X_train = train[:, :-1]
y_train = train[:, -1]

X_test = test[:,:-1]
y_test = test[:,-1]

In [10]:
from sklearn.utils.class_weight import compute_class_weight
class_weights = compute_class_weight(class_weight = 'balanced', classes = np.unique(y_train), y=y_train)
# 创建随机森林分类器
rf_clf = RandomForestClassifier(n_estimators=100,class_weight={0: class_weights[0], 1: class_weights[1], 2: class_weights[2]}, random_state=42)


# 训练模型
rf_clf.fit(X_train, y_train)

# 进行预测
y_pred = rf_clf.predict(X_test)

# 计算准确率和混淆矩阵
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)


Accuracy: 0.6210526315789474
Confusion Matrix:
[[26  4  0]
 [ 3 30  1]
 [ 2 26  3]]


In [8]:
from sklearn.metrics import roc_curve, auc, precision_recall_curve
# 进行预测
y_pred_score = rf_clf.predict_proba(X_test)
y_pred_score = pd.DataFrame(y_pred_score,columns = ['health','hb','hc'])
y_pred_score.to_csv('./RF/RF_pre_score.csv')
pd.DataFrame(y_pred).to_csv("./RF/RF_pres.csv")

### 扩增后的数据

In [ ]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [14]:

h_train = pd.read_csv('./amplified_data/train_h.csv', header= None)
h_train['label'] = 0
y_train = pd.read_csv('./amplified_data/train_y.csv', header= None)
y_train['label'] =1
b_train = pd.read_csv('./amplified_data/train_b.csv', header= None)
b_train['label'] =2
h_test = pd.read_csv('./amplified_data/test_h.csv', header= None)
h_test['label'] = 0
y_test = pd.read_csv('./amplified_data/test_y.csv', header= None)
y_test['label'] = 1
b_test = pd.read_csv('./amplified_data/test_b.csv', header= None)
b_test['label'] = 2
print(
    h_train.shape,
    y_train.shape,
    b_train.shape,
    h_test.shape,
    y_test.shape,
    b_test.shape
)



(440, 1775) (440, 1775) (400, 1775) (30, 1775) (34, 1775) (31, 1775)


In [16]:
train=np.concatenate((h_train,y_train,b_train),0)
test=np.concatenate((h_test,y_test,b_test),0)

X_train = train[:, :-1]
y_train = train[:, -1]

X_test = test[:,:-1]
y_test = test[:,-1]

In [17]:
from sklearn.utils.class_weight import compute_class_weight

# creat model
rf_clf = RandomForestClassifier(n_estimators=100, max_depth = 3,random_state=2)


# Training 
rf_clf.fit(X_train, y_train)

# Test
y_pred = rf_clf.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)


Accuracy: 0.5894736842105263
Confusion Matrix:
[[26  3  1]
 [10 17  7]
 [ 8 10 13]]


In [18]:
from sklearn.metrics import roc_curve, auc, precision_recall_curve

y_pred_score = rf_clf.predict_proba(X_test)
y_pred_score = pd.DataFrame(y_pred_score,columns = ['health','hb','hc'])
y_pred_score.to_csv('./A_RF/A_RF_pre_score.csv')
pd.DataFrame(y_pred).to_csv("./A_RF/A_RF_pres.csv")